
Currently Loaded Modules:
  1) intel/18.0.2   4) autotools/1.2   7) TACC
  2) impi/18.0.2    5) cmake/3.16.1    8) python3/3.7.0
  3) git/2.24.1     6) xalt/2.9.6      9) cuda/11.0     (g)

  Where:
   g:  built for GPU

 

Traceback (most recent call last):
  File "src/test.py", line 48, in <module>
    n2n.test(test_loader, show=params.show_output)
  File "/work2/08261/evanat/maverick2/n2n-pytorch/src/noise2noise.py", line 164, in test
    for batch_idx, (source, target) in enumerate(test_loader):
  File "/work2/08261/evanat/maverick2/n2n-pytorch/.venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/work2/08261/evanat/maverick2/n2n-pytorch/.venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/work2/08261/evanat/maverick2/n2n-pytorch/.venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/work2/08261/evanat/maverick2/n2n-pytorch/.venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/work2/08261/evanat/maverick2/n2n-pytorch/src/datasets.py", line 235, in __getitem__
    tmp = self._corrupt(img)
  File "/work2/08261/evanat/maverick2/n2n-pytorch/src/datasets.py", line 216, in _corrupt
    return self._add_noise(img)
  File "/work2/08261/evanat/maverick2/n2n-pytorch/src/datasets.py", line 148, in _add_noise
    noise_img = b.create_image(img, p=self.noise_param, style='b')
  File "/work2/08261/evanat/maverick2/n2n-pytorch/src/bern_utils_PIL.py", line 39, in create_image
    if crop > 10:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
